#!/usr/bin/env python3
"""Export GPU-26-Years.csv + CPI table to web-ready JSON and data.js (file:// safe)."""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent
CSV_PATH = ROOT / "data" / "GPU-26-Years.csv"
SITE_DATA = ROOT.parent / "docs" / "gpu-26-years" / "data"
SITE_JS = ROOT.parent / "docs" / "gpu-26-years" / "js"

# US CPI-U annual averages (1982-84=100) — same series as the notebook
CPI_ANNUAL = {
    2000: 172.2,
    2001: 177.1,
    2002: 179.9,
    2003: 184.0,
    2004: 188.9,
    2005: 195.3,
    2006: 201.6,
    2007: 207.3,
    2008: 215.3,
    2009: 214.5,
    2010: 218.1,
    2011: 224.9,
    2012: 229.6,
    2013: 233.0,
    2014: 236.7,
    2015: 237.0,
    2016: 240.0,
    2017: 245.1,
    2018: 251.1,
    2019: 255.7,
    2020: 258.8,
    2021: 271.0,
    2022: 292.7,
    2023: 304.7,
    2024: 313.7,
    2025: 321.9,
    2026: 330.9,
}

TARGET_YEAR = 2025
TARGET_CPI = CPI_ANNUAL[TARGET_YEAR]


def row_to_record(row: pd.Series) -> dict:
    def num(key):
        v = row.get(key)
        if pd.isna(v) or v == "":
            return None
        try:
            return float(v)
        except (TypeError, ValueError):
            return None

    def intval(key):
        v = num(key)
        return int(v) if v is not None else None

    return {
        "year": intval("Released_Year"),
        "month": intval("Released_Month"),
        "manufacturer": str(row.get("Manufacturer") or ""),
        "oem": str(row.get("OEM") or ""),
        "msrp": num("MSRP_USD"),
        "name": str(row.get("GPU_Name") or ""),
        "architecture": str(row.get("Architecture") or ""),
        "codename": str(row.get("Codename") or ""),
        "memory_gb": num("Memory_GB"),
        "memory_type": str(row.get("Memory_Type") or ""),
        "memory_bus": str(row.get("Memory_Bus_Width") or ""),
        "bandwidth_gbs": num("Memory_Bandwidth_GBs"),
        "base_clock": num("Base_Clock_MHz"),
        "boost_clock": num("Boost_Clock_MHz"),
        "cuda_cores": num("CUDA_Cores"),
        "stream_processors": num("Stream_Processors"),
        "tdp_w": num("TDP_W"),
        "process_nm": num("Process_nm"),
        "transistors_m": num("Transistors_M"),
        "die_size_mm2": num("Die_Size_mm2"),
        "tflops": num("TFLOPS_FP32"),
        "pcie": str(row.get("PCIe") or ""),
    }


def main() -> None:
    SITE_DATA.mkdir(parents=True, exist_ok=True)
    SITE_JS.mkdir(parents=True, exist_ok=True)

    df = pd.read_csv(CSV_PATH)
    records = [row_to_record(r) for _, r in df.iterrows()]

    payload = {
        "meta": {
            "title": "GPUs the last 26 years",
            "source_csv": "GPU-26-Years.csv",
            "target_year": TARGET_YEAR,
            "target_cpi": TARGET_CPI,
            "row_count": len(records),
            "year_min": min(r["year"] for r in records if r["year"]),
            "year_max": max(r["year"] for r in records if r["year"]),
        },
        "cpi": {str(k): v for k, v in CPI_ANNUAL.items()},
        "gpus": records,
    }

    json_path = SITE_DATA / "gpu-26-years.json"
    json_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")

    # file://-safe: classic script assigns globals (no fetch / no ES modules)
    data_js = (
        "/* Auto-generated by GPUs-the-last-26-years/export_web_data.py — do not edit by hand */\n"
        "window.GPU_DATASET = "
        + json.dumps(payload, separators=(",", ":"))
        + ";\n"
    )
    (SITE_JS / "gpu-dataset.js").write_text(data_js, encoding="utf-8")

    print(f"Wrote {json_path} ({len(records)} rows)")
    print(f"Wrote {SITE_JS / 'gpu-dataset.js'}")


if __name__ == "__main__":
    main()
